# Generated by Django 3.1.6 on 2021-02-11 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('I_GENE_HLDAY', 'Igene-Holiday'), ('WEEKEND', 'Weekend')], max_length=64)),
                ('date', models.DateField(unique=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
