# Generated by Django 3.1.6 on 2021-02-11 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('usertype', models.CharField(choices=[('ARTIST', 'artist'), ('PRODUCTION', 'production'), ('PRO-CO', 'project co-ordinator'), ('PRO-TL', 'project lead'), ('PRO-SUP', 'project supervisor'), ('IT-SUPPORT', 'it-support')], max_length=50)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('username', models.CharField(max_length=255)),
                ('dept', models.CharField(choices=[('PAINT', 'Paint & Prep'), ('MATCH', 'Match-move'), ('ROTO', 'Roto'), ('COMP', 'Comp'), ('MANG', 'Management')], default='MANG', max_length=255)),
                ('designation', models.CharField(max_length=255, null=True)),
                ('doj', models.DateField(null=True)),
                ('igene_id', models.CharField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('staff', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
