# Generated by Django 3.1.6 on 2021-02-11 09:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intime', models.TimeField(null=True)),
                ('outtime', models.TimeField(null=True)),
                ('date', models.DateField()),
                ('review_notes', models.CharField(max_length=500, null=True)),
                ('approved', models.BooleanField(null=True)),
                ('total_hours', models.DurationField(blank=True, null=True)),
                ('updating_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dailyupdate', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Dailies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slottype', models.CharField(choices=[('PROD_SHOT', 'Production Shot'), ('TEST_SHOT', 'Test Shot'), ('TRAIN', 'Training'), ('I/O', 'I/O Downtime'), ('MEET', 'Meeting'), ('SYS', 'System Failure'), ('NET', 'Network Issue'), ('RENDER', 'Rendering Downtime'), ('PERM', 'Permission'), ('LEAVE', 'Leave'), ('H_LEAVE', 'Half Leave')], max_length=80)),
                ('slottime', models.DurationField()),
                ('status_accepted', models.BooleanField(null=True)),
                ('shot', models.CharField(blank=True, max_length=100, null=True)),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('update', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dailies', to='artist.dailyupdate')),
            ],
        ),
        migrations.AddConstraint(
            model_name='dailyupdate',
            constraint=models.UniqueConstraint(fields=('date', 'updating_user'), name='unique_update_for_date'),
        ),
    ]
