# Generated by Django 3.1.6 on 2021-03-11 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0002_auto_20210216_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyupdate',
            name='artist_notes',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
